Repository SmartBear/swaggerhub-cli, pull requests merged in 2023-04, with the labels that each got.

#281 Upgrade to @oclif/core + fix GHA Workflows
  .eslintrc
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/build-main-publish-npm.yaml
  .github/workflows/build-main-push-to-aws.yaml
  .github/workflows/build-main.yaml
  .github/workflows/pull-request.yaml
  .github/workflows/release-on-github.yaml
  README.md
  bin/run
  package-lock.json
  package.json
  src/commands/api/create.js
  src/commands/api/delete.js
  src/commands/api/get.js
  src/commands/api/publish.js
  src/commands/api/setdefault.js
  src/commands/api/unpublish.js
  src/commands/api/update.js
  src/commands/api/validate.js
  src/commands/domain/create.js
  src/commands/domain/delete.js
  src/commands/domain/get.js
  src/commands/domain/publish.js
  src/commands/domain/setdefault.js
  src/commands/domain/unpublish.js
  src/commands/domain/update.js
  src/commands/integration/create.js
  src/commands/integration/delete.js
  src/commands/integration/execute.js
  src/commands/integration/get.js
  src/commands/integration/list.js
  src/commands/integration/update.js
  src/commands/project/api/add.js
  src/commands/project/api/remove.js
  src/commands/project/create.js
  src/commands/project/delete.js
  src/commands/project/domain/add.js
  src/commands/project/domain/remove.js
  src/commands/project/get.js
  src/commands/project/list.js
  src/commands/project/member/list.js
  src/help.js
  src/index.js
  src/support/command/base-command.js
  src/support/command/handle-response.js
  src/support/command/parse-input.js
  src/support/command/update-command.js
  src/utils/definitions.js
  test/commands/api/publish.test.js
  test/support/parse-input.test.js
Labels: enhancement

#287 Fix release job and regenerate lock file
  .github/workflows/release-on-github.yaml
  package-lock.json
Labels: ignore-for-release

#288 Remove lodash and update tests
  package-lock.json
  package.json
  src/config/index.js
  src/support/http/index.js
  src/utils/general.js
  test/commands/api/validate.test.js
  test/support/config.test.js
  test/support/inquirer.test.js
  test/utils/general.test.js
Labels: ignore-for-release

#291 Update Docker base image to node 18
  .github/action/entrypoint.sh
  Dockerfile
Labels: bug-fix

#292 Update versions in documentation
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/action/README.md
Labels: documentation

#295 Use example from docs to fix GH Action
  .github/action/entrypoint.sh
Labels: bug-fix
