Repository SmartBear/swaggerhub-cli, pull requests merged in 2023-03, with the labels that each got.

#283 Fix exit codes for `api:validate` command
  src/commands/api/validate.js
  test/commands/api/validate.test.js
Labels: bug-fix

#284 Add `-c/--fail-on-critical` flag to `api:validate` command
  README.md
  src/commands/api/validate.js
  test/commands/api/validate.test.js
Labels: enhancement

#285 Update main branch name
  .github/workflows/build-main-publish-npm.yaml
  .github/workflows/build-main-push-to-aws.yaml
  .github/workflows/build-main.yaml
  .github/workflows/pull-request.yaml
  README.md
  src/commands/integration/create.js
Labels: ignore-for-release
